more linting

diff --git a/.github/workflows/poem_linter.yml b/.github/workflows/poem_linter.yml
--- a/.github/workflows/poem_linter.yml
+++ b/.github/workflows/poem_linter.yml
@@ -32,6 +32,16 @@ jobs:
     - name: Run script
       - run: |
           mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
+          status = 0
           for added_modified_file in "${added_modified_files[@]}"; do
             python ./.github/scripts/linter.py '${added_modified_file}'"
+            status = status | $?
           done
+          if [ $status -eq 0 ]
+          then
+            echo "Linting successful"
+            exit 0
+          else
+            echo "Linting error"
+            exit 1
+          fi
